package com.github.dashframe.models.json;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.github.dashframe.models.json.EpicGamesFreeGamesWidgetConfiguration;
import com.github.dashframe.models.json.EpicGamesFriendsListWidgetConfiguration;
import com.github.dashframe.models.json.RssFeedWidgetConfiguration;
import com.github.dashframe.models.json.SteamFriendsListWidgetConfiguration;
import com.github.dashframe.models.json.SteamGameNewsWidgetConfiguration;
import com.github.dashframe.models.json.SteamGamePopulationWidgetConfiguration;
import com.github.dashframe.models.json.TwitchFollowedChannelsWidgetConfiguration;
import com.github.dashframe.models.json.WeatherTimeWidgetConfiguration;
import com.github.dashframe.models.json.YouTubeChannelStatisticsWidgetConfiguration;
import com.github.dashframe.models.json.YouTubeSubscribedChannelsWidgetConfiguration;
import com.github.dashframe.models.json.YouTubeVideoStatisticsWidgetConfiguration;
import com.github.dashframe.models.json.YouTubeVideoStatisticsWidgetConfigurationAllOfParameters;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.*;
import java.util.Objects;
import javax.annotation.Generated;
import javax.validation.Valid;
import javax.validation.constraints.*;

@JsonIgnoreProperties(
    value = "type", // ignore manually set type, it will be automatically generated by Jackson during serialization
    allowSetters = true // allows the type to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    {
        @JsonSubTypes.Type(
            value = EpicGamesFreeGamesWidgetConfiguration.class,
            name = "EpicGamesFreeGamesWidgetConfiguration"
        ),
        @JsonSubTypes.Type(
            value = EpicGamesFriendsListWidgetConfiguration.class,
            name = "EpicGamesFriendsListWidgetConfiguration"
        ),
        @JsonSubTypes.Type(value = RssFeedWidgetConfiguration.class, name = "RssFeedWidgetConfiguration"),
        @JsonSubTypes.Type(
            value = SteamFriendsListWidgetConfiguration.class,
            name = "SteamFriendsListWidgetConfiguration"
        ),
        @JsonSubTypes.Type(value = SteamGameNewsWidgetConfiguration.class, name = "SteamGameNewsWidgetConfiguration"),
        @JsonSubTypes.Type(
            value = SteamGamePopulationWidgetConfiguration.class,
            name = "SteamGamePopulationWidgetConfiguration"
        ),
        @JsonSubTypes.Type(
            value = TwitchFollowedChannelsWidgetConfiguration.class,
            name = "TwitchFollowedChannelsWidgetConfiguration"
        ),
        @JsonSubTypes.Type(value = WeatherTimeWidgetConfiguration.class, name = "WeatherTimeWidgetConfiguration"),
        @JsonSubTypes.Type(
            value = YouTubeChannelStatisticsWidgetConfiguration.class,
            name = "YouTubeChannelStatisticsWidgetConfiguration"
        ),
        @JsonSubTypes.Type(
            value = YouTubeSubscribedChannelsWidgetConfiguration.class,
            name = "YouTubeSubscribedChannelsWidgetConfiguration"
        ),
        @JsonSubTypes.Type(
            value = YouTubeVideoStatisticsWidgetConfiguration.class,
            name = "YouTubeVideoStatisticsWidgetConfiguration"
        ),
        @JsonSubTypes.Type(value = EpicGamesFreeGamesWidgetConfiguration.class, name = "epic_games/free_games"),
        @JsonSubTypes.Type(value = EpicGamesFriendsListWidgetConfiguration.class, name = "epic_games/friends_list"),
        @JsonSubTypes.Type(value = RssFeedWidgetConfiguration.class, name = "rss/feed"),
        @JsonSubTypes.Type(value = SteamFriendsListWidgetConfiguration.class, name = "steam/friends_list"),
        @JsonSubTypes.Type(value = SteamGameNewsWidgetConfiguration.class, name = "steam/game_news"),
        @JsonSubTypes.Type(value = SteamGamePopulationWidgetConfiguration.class, name = "steam/game_population"),
        @JsonSubTypes.Type(value = TwitchFollowedChannelsWidgetConfiguration.class, name = "twitch/followed_channels"),
        @JsonSubTypes.Type(value = WeatherTimeWidgetConfiguration.class, name = "weather_time/default"),
        @JsonSubTypes.Type(
            value = YouTubeChannelStatisticsWidgetConfiguration.class,
            name = "youtube/channel_statistics"
        ),
        @JsonSubTypes.Type(
            value = YouTubeSubscribedChannelsWidgetConfiguration.class,
            name = "youtube/subsribed_channels"
        ),
        @JsonSubTypes.Type(value = YouTubeVideoStatisticsWidgetConfiguration.class, name = "youtube/video_statistics"),
    }
)
@Generated(
    value = "org.openapitools.codegen.languages.SpringCodegen",
    date = "2022-11-08T15:27:52.118173200+01:00[Europe/Paris]"
)
public interface WidgetConfiguration {
    public String getType();
}
