name: Main

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup jdk 17
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Gradle and Build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: build --scan
          cache-read-only: false
        env:
          GRADLE_TOS_AGREE: yes

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check Formatting
        shell: bash
        run: npx prettier --check .

      - name: ESLint
        shell: bash
        working-directory: front
        run: |
          npm install
          npm run lint
